version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      gradle-dependencies:
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
    groups:
      github-actions:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - area:ci
