naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'

complexity:
  LongParameterList:
    allowedFunctionParameters: 8
    allowedConstructorParameters: 8
  TooManyFunctions:
    allowedFunctionsPerClass: 25
    allowedFunctionsPerInterface: 25
    allowedFunctionsPerObject: 25

style:
  MagicNumber:
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '100'
      - '1000'
    ignoreEnums: true
    ignoreRanges: true
    ignoreAnnotation: true
  MaxLineLength:
    maxLineLength: 120
  ReturnCount:
    max: 4
  WildcardImport:
    excludeImports:
      - 'androidx.compose.foundation.layout.*'
      - 'androidx.compose.material3.*'
      - 'androidx.compose.runtime.*'
      - 'androidx.compose.ui.*'
  ExpressionBodySyntax:
    active: true
    includeLineWrapping: true

Compose:
  ModifierMissing:
    active: true

ktlint:
  active: true
  android: true
  autoCorrect: true
  MaximumLineLength:
    maxLineLength: 120
